import Image from "next/image";
import Link from "next/link";
import {CTA, gear, Layout, SearchBox} from "./components";

export default function Home(){return <Layout>
  <section className="hero"><div className="heroCopy"><span className="eyebrow">Paquete completo · hasta 4 personas</span><h1>Todo para acampar.<br/><em>Sin tener que comprarlo.</em></h1><p>Primera noche por <strong>$1,999 MXN</strong> y noches adicionales por solo <strong>$799 MXN</strong>. IVA incluido.</p><div className="heroActions"><Link className="primary" href="/reservar">Elegir fechas</Link><Link className="textLink" href="/servicios">Ver qué incluye →</Link></div></div><div className="heroArt"><Image priority fill sizes="(max-width: 900px) 100vw, 48vw" src="/camping-hero-v2.webp" alt="Paquete de renta con casa de campaña, dos sillas, hielera, lámparas, tapete y botiquín"/></div></section>
  <SearchBox/>
  <section className="packageSpotlight"><div><span className="eyebrow">Una sola renta. Todo lo esencial.</span><h2>Paquete básico</h2><p className="bigPrice"><b>$1,999</b> MXN <small>primera noche</small></p><p><strong>Noches adicionales por $799 MXN.</strong> Ideal para una escapada en pareja, familia o grupo de hasta cuatro personas. IVA incluido.</p><Link className="primary" href="/reservar">Calcular estancia</Link></div><ul><li><span>⛺</span><b>Casa de campaña</b><small>Para hasta 4 personas</small></li><li><span>♧</span><b>2 sillas</b><small>Para descansar en exterior</small></li><li><span>☼</span><b>2 lámparas nocturnas</b><small>Iluminación para el campamento</small></li><li><span>❄</span><b>Hielera</b><small>Para alimentos y bebidas</small></li><li><span>▰</span><b>Colchón inflable</b><small>Mayor comodidad al dormir</small></li><li><span>✚</span><b>Botiquín</b><small>Equipo básico de primeros auxilios</small></li></ul></section>
  <section className="steps"><div><span className="eyebrow">Así de fácil</span><h2>De la reserva al campamento<br/>en tres pasos</h2></div><ol><li><b>01</b><div><h3>Selecciona la fecha</h3><p>Elige el inicio de tu campamento y dinos en qué domicilio entregamos.</p></div></li><li><b>02</b><div><h3>Recíbelo un día antes</h3><p>Llevamos el paquete a tu domicilio en CDMX, EDOMEX o Pachuca.</p></div></li><li><b>03</b><div><h3>Regresa y nosotros recogemos</h3><p>Pasamos por el equipo al mismo domicilio donde lo entregamos. Tu depósito se devuelve al recibir todo completo.</p></div></li></ol></section>
  <section className="locationsStrip"><span>Entrega en</span><Link href="/ubicaciones">CDMX</Link><i>•</i><Link href="/ubicaciones">Estado de México</Link><i>•</i><Link href="/ubicaciones">Pachuca</Link></section>
  <CTA/>
</Layout>}
